### ISSUE TITLE
Local Packages Installation

### ISSUE THREAD

**Issue by bsrdl** [akkikiki/diff_joint_estimate#1]
Hi,
 
When I try to run pip install -r  requirements.txt, I met an error "ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode" when installing local packages (pip install -e .). 

I somehow handled this error (skipped installing local packages and change the directory of train_model.py ), but this time when I tried to run train_model.py, I got this error:

          File "diff_joint_estimate/src/utils.py", line 101, 
          in accuracy return correct / mask.sum().item()
          ZeroDivisionError: float division by zero

This might occur due to I didn't install local packages, but I'm not sure. 
I tried to run train_model.py with different parameters, all of them raised ZeroDivisionError.

I hope my description is as clear as I can, and wish you could help me. Thank you very much!

**Comment by akkikiki** [comment]
Hi, 
Sorry, I haven't written a good README on how to run out-of-the-box, so let me work on setting up `setup.py` and other files to make it work.
I'll ping you here once it's ready

**Comment by akkikiki** [comment]
@bsrdl Just added more stuff in https://github.com/akkikiki/diff_joint_estimate/pull/2 so would you mind checking the README and see if your issue is resolved?

The direct cause of `ZeroDivisionError` is missing the Cambridge Readability Dataset and running `sh src/scripts/download_data.sh` should resolve it.

**Comment by bsrdl** [comment]
My issue is resolved. Thank you so much!

**Comment by akkikiki** [comment]
Great to hear that!
